### PR TITLE
fix: update ubi base images

### PR DESCRIPTION
**Pull request by dimakis**
## Related issue number

Closes https://github.com/project-codeflare/codeflare-operator/issues/351

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by dimakis** [comment]
@astefanutti @anishasthana

**Review by tedhtchang — COMMENTED** [review]
@dimakis The tag 1.19 points to a newest [1.19.13-2](https://catalog.redhat.com/software/containers/rhel8/go-toolset/5b9c810add19c70b45cbd666?architecture=amd64&image=652d47582fd993af22f76402&container-tabs=overview) at the moment but may point to another newer version later without passing the CI tests. Is this the behavior you want ?

**Comment by astefanutti** [comment]
@tedhtchang I agree using a non-rolling tag would be useful so we have reproducible builds. So maybe @dimakis you can use the 1.19.13-2 tag. On the other hand, this is a temporary patch anyway, as it'll be superseded by the changes from upstream ray-project/kuberay#1540 once that fork is rebased.

**Comment by anishasthana** [comment]
I'd like to think about the versioning/branching a little bit before we merge this.

**Pull request closed without merging**
